### ISSUE TITLE
Nested variables not resolving.

### ISSUE THREAD

**Issue by muheetnature9** [syncloop-dev/syncloop-core#143]
In Transformer or any conditional steps such as redo, if-else is not resolving expressions if the expressions have variables.

Example: if the pipeline has the following data A=B, B=C, and C=D, its expression is mentioned as #{#{#{A}}} is resolving as “null” whereas it is supposed to resolve as “D”.

**Comment by RohanMishra315** [comment]
Hey @Divyanshgurtoo @muheetnature9  Do you mean does this file has problem  ,right ?
src/com/eka/middleware/flow/Transformer.java

**Comment by syncloop-dev** [comment]
Hi @RohanMishra315, 
There is not issue in current release & Transformer.java. This is a feature which we are releasing in version 1.6. The fix is available in branch [https://github.com/syncloop-dev/syncloop-core/tree/release/1.6]. You can start using this now.

Thanks

**Comment by RohanMishra315** [comment]
Ok then , I thought there is issue here. I'll look into the new release. Thanks

**Comment by UtkarshUmre** [comment]
Since no one is assigned, and this is also labeled as a good first issue, along with the ongoing SyncLoop Open Source Challenge, please assign this task to me

**Comment by syncloop-dev** [comment]
Hi,

@UtkarshUmre Thank you for your interest. This issue is already resolved in release/1.6. You can pick another issue from issues list.
