### ISSUE TITLE
Not able to set an element in an array based on the index value. 

### ISSUE THREAD

**Issue by muheetnature9** [syncloop-dev/syncloop-core#148]
An array element can be mapped based on the index to a variable **but the reverse is not working.**. Suppose we want to read the value at index 5 in an array **arTest**. 

We can directly specify the index by selecting the array and variable mapping and clicking the custom mapping configuration icon. By clicking on the index which is default as 0, it can be changed to any valid index and accordingly, the element at that index can be assigned to the variable. 

While trying to assign the value of the variable to an array index, it is not working. It can be also put as array element updation at any index is not working whereas reading elements/values at any array index is working. 

![image](https://github.com/syncloop-dev/syncloop-core/assets/139915301/3bb28547-8274-42ed-97c4-8e87a139f2d4)

**Comment by Wassaf001** [comment]
@syncloop-dev claim.
